In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('iris.csv')

In [3]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [4]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

In [5]:
df['species']=df['species'].replace({
    0:'iris set',
    1: 'iris sen',
    2: 'iris sem'
})

In [7]:
df.groupby('species').describe()

                sepal length (cm)                                              \
                            count   mean       std  min    25%  50%  75%  max
species
Iris-setosa                  50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor              50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica               50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepal width (cm)         ... petal length (cm)       \
                           count   mean  ...               75%  max
species                                  ...
Iris-setosa                 50.0  3.428  ...             1.575  1.9
Iris-versicolor             50.0  2.770  ...             4.600  5.1
Iris-virginica              50.0  2.974  ...             5.875  6.9

                petal width (cm)
                           count   mean       std  min  25%  50%  75%  max
species
Iris-setosa                 50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6
Iris-versicolor             50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica              50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [8]:
df.groupby('species').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
Iris-setosa,5.006,3.428,1.462,0.246
Iris-versicolor,5.936,2.770,4.260,1.326
Iris-virginica,6.588,2.974,5.552,2.026

In [9]:
df.groupby('species').std()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
Iris-setosa,0.352490,0.379064,0.173664,0.105386
Iris-versicolor,0.516171,0.313798,0.469911,0.197753
Iris-virginica,0.635880,0.322497,0.551895,0.274650

In [10]:
df.groupby('species').median()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
Iris-setosa,5.0,3.4,1.50,0.2
Iris-versicolor,5.9,2.8,4.35,1.3
Iris-virginica,6.5,3.0,5.55,2.0

In [11]:
df.groupby('species').max()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
Iris-setosa,5.8,4.4,1.9,0.6
Iris-versicolor,7.0,3.4,5.1,1.8
Iris-virginica,7.9,3.8,6.9,2.5

In [12]:
df.groupby('species').min()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
Iris-setosa,4.3,2.3,1.0,0.1
Iris-versicolor,4.9,2.0,3.0,1.0
Iris-virginica,4.9,2.2,4.5,1.4

In [13]:
df.describe

<bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

            species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 5 columns]>

In [14]:
print(df.describe())

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            5.843333          3.057333           3.758000
std             0.828066          0.435866           1.765298
min             4.300000          2.000000           1.000000
25%             5.100000          2.800000           1.600000
50%             5.800000          3.000000           4.350000
75%             6.400000          3.300000           5.100000
max             7.900000          4.400000           6.900000

       petal width (cm)
count        150.000000
mean           1.199333
std            0.762238
min            0.100000
25%            0.300000
50%            1.300000
75%            1.800000
max            2.500000

In [19]:
grouped = df.groupby('species')
print(grouped.describe())
print(df.describe)

                sepal length (cm)                                              \
                            count   mean       std  min    25%  50%  75%  max
species
Iris-setosa                  50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor              50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica               50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepal width (cm)         ... petal length (cm)       \
                           count   mean  ...               75%  max
species                                  ...
Iris-setosa                 50.0  3.428  ...             1.575  1.9
Iris-versicolor             50.0  2.770  ...             4.600  5.1
Iris-virginica              50.0  2.974  ...             5.875  6.9

                petal width (cm)
                           count   mean       std  min  25%  50%  75%  max
species
Iris-setosa                 50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6
Iris-versicolor             50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica              50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]
<bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

            species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 5 columns]>

In [20]:
print(grouped.quantile([0.25, 0.50, 0.75]))

                      sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
Iris-setosa     0.25              4.800             3.200              1.400
                0.50              5.000             3.400              1.500
                0.75              5.200             3.675              1.575
Iris-versicolor 0.25              5.600             2.525              4.000
                0.50              5.900             2.800              4.350
                0.75              6.300             3.000              4.600
Iris-virginica  0.25              6.225             2.800              5.100
                0.50              6.500             3.000              5.550
                0.75              6.900             3.175              5.875

                      petal width (cm)
species
Iris-setosa     0.25               0.2
                0.50               0.2
                0.75               0.3
Iris-versicolor 0.25               1.2
                0.50               1.3
                0.75               1.5
Iris-virginica  0.25               1.8
                0.50               2.0
                0.75               2.3

In [23]:
grouped.quantile([0.25,0.35,0.50])

                      sepal length (cm)  sepal width (cm)  petal length (cm)  \
species
Iris-setosa     0.25              4.800             3.200              1.400
                0.35              4.900             3.300              1.400
                0.50              5.000             3.400              1.500
Iris-versicolor 0.25              5.600             2.525              4.000
                0.35              5.700             2.700              4.100
                0.50              5.900             2.800              4.350
Iris-virginica  0.25              6.225             2.800              5.100
                0.35              6.300             2.800              5.215
                0.50              6.500             3.000              5.550

                      petal width (cm)
species
Iris-setosa     0.25               0.2
                0.35               0.2
                0.50               0.2
Iris-versicolor 0.25               1.2
                0.35               1.3
                0.50               1.3
Iris-virginica  0.25               1.8
                0.35               1.9
                0.50               2.0