In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from  sklearn.metrics import accuracy_score
from  sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [10]:
df = pd.read_csv('Social_Network_Ads.csv')

In [11]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [12]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [13]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [14]:
df = pd.read_csv('Social_Network_Ads.csv')

In [17]:
x = df[['Age','EstimatedSalary']]
y = df['Purchased']

In [18]:
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size = 0.25,
    random_state = 5
)

In [19]:
model = LogisticRegression()

In [20]:
model.fit(x_train,y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(x_test)

In [27]:
Accuracy = accuracy_score(y_test,y_pred)

In [28]:
Accuracy

0.86

In [30]:
precision = precision_score(y_test,y_pred)
precision

0.8125

In [31]:
Error_rate = 1-Accuracy 
Error_rate

0.14

In [32]:
cm  = confusion_matrix(y_test,y_pred)
cm

array([[60,  6],
       [ 8, 26]])

In [33]:
recall = recall_score(y_test,y_pred)

In [34]:
recall

0.7647058823529411

In [36]:
TN = cm[0][0]
TN

np.int64(60)

In [37]:
TP = cm[1][1]
TP

np.int64(26)

In [38]:
FP = cm[0][1]
FP

np.int64(6)

In [ ]:
FN = cm[1][0]
FN