In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = {
    'Name': ['Amit', 'Riya', 'Karan', 'Sneha', 'Rahul',
             'Pooja', 'Neha', 'Arjun', 'Vikas', 'Meera'],

    'Math': [85, 90, np.nan, 35, 95,
             88, 76, 500, 84, 91],

    'Science': [78, 89, 84, 40, np.nan,
                92, 75, 85, 80, 88],

    'English': [74, 95, 82, 45, 90,
                87, np.nan, 89, 77, 93]
}

df = pd.DataFrame(data)

print(df)

    Name   Math  Science  English
0   Amit   85.0     78.0     74.0
1   Riya   90.0     89.0     95.0
2  Karan    NaN     84.0     82.0
3  Sneha   35.0     40.0     45.0
4  Rahul   95.0      NaN     90.0
5  Pooja   88.0     92.0     87.0
6   Neha   76.0     75.0      NaN
7  Arjun  500.0     85.0     89.0
8  Vikas   84.0     80.0     77.0
9  Meera   91.0     88.0     93.0

In [3]:
df.isnull().sum()

Name       0
Math       1
Science    1
English    1
dtype: int64

In [4]:
df['Math'] = df['Math'].fillna(df['Math'].mean())

In [5]:
df['Science'] = df['Science'].fillna(df['Science'].mean())

In [6]:
df['English'] = df['English'].fillna(df['English'].mean())

In [7]:
df.isnull().sum()

Name       0
Math       0
Science    0
English    0
dtype: int64

In [8]:
df.describe()

             Math    Science    English
count   10.000000  10.000000  10.000000
mean   127.111111  79.000000  81.333333
std    132.923073  14.719601  14.460675
min     35.000000  40.000000  45.000000
25%     84.250000  78.250000  78.083333
50%     89.000000  82.000000  84.500000
75%     94.000000  87.250000  89.750000
max    500.000000  92.000000  95.000000

In [9]:
df

    Name        Math  Science    English
0   Amit   85.000000     78.0  74.000000
1   Riya   90.000000     89.0  95.000000
2  Karan  127.111111     84.0  82.000000
3  Sneha   35.000000     40.0  45.000000
4  Rahul   95.000000     79.0  90.000000
5  Pooja   88.000000     92.0  87.000000
6   Neha   76.000000     75.0  81.333333
7  Arjun  500.000000     85.0  89.000000
8  Vikas   84.000000     80.0  77.000000
9  Meera   91.000000     88.0  93.000000

In [10]:
df['Math'] = np.where(df['Math'] > 100,df['Math'].mean(),df['Math'])

In [14]:
df

    Name        Math  Science    English
0   Amit   85.000000     78.0  74.000000
1   Riya   90.000000     89.0  95.000000
2  Karan  127.111111     84.0  82.000000
3  Sneha   35.000000     40.0  45.000000
4  Rahul   95.000000     79.0  90.000000
5  Pooja   88.000000     92.0  87.000000
6   Neha   76.000000     75.0  81.333333
7  Arjun  127.111111     85.0  89.000000
8  Vikas   84.000000     80.0  77.000000
9  Meera   91.000000     88.0  93.000000

In [15]:
df['Math'] = np.where(df['Math'] > 100,df['Math'].mean(),df['Math'])

In [16]:
df

    Name       Math  Science    English
0   Amit  85.000000     78.0  74.000000
1   Riya  90.000000     89.0  95.000000
2  Karan  89.822222     84.0  82.000000
3  Sneha  35.000000     40.0  45.000000
4  Rahul  95.000000     79.0  90.000000
5  Pooja  88.000000     92.0  87.000000
6   Neha  76.000000     75.0  81.333333
7  Arjun  89.822222     85.0  89.000000
8  Vikas  84.000000     80.0  77.000000
9  Meera  91.000000     88.0  93.000000

In [23]:
df['Math-Normalized']= ((df['Math']-df['Math'].min())/ (df['Math'].max()-df['Math'].min())) 
df[['Math','Math-Normalized']]

        Math  Math-Normalized
0  85.000000         0.833333
1  90.000000         0.916667
2  89.822222         0.913704
3  35.000000         0.000000
4  95.000000         1.000000
5  88.000000         0.883333
6  76.000000         0.683333
7  89.822222         0.913704
8  84.000000         0.816667
9  91.000000         0.933333

In [24]:
df['Math-Normalized'] = ((df['Math']-df['Math'].min())/(df['Math'].max()-df['Math'].min()))
df[['Math', 'Math-Normalized']]

        Math  Math-Normalized
0  85.000000         0.833333
1  90.000000         0.916667
2  89.822222         0.913704
3  35.000000         0.000000
4  95.000000         1.000000
5  88.000000         0.883333
6  76.000000         0.683333
7  89.822222         0.913704
8  84.000000         0.816667
9  91.000000         0.933333

In [25]:
df

    Name       Math  Science    English  Math-Normalized
0   Amit  85.000000     78.0  74.000000         0.833333
1   Riya  90.000000     89.0  95.000000         0.916667
2  Karan  89.822222     84.0  82.000000         0.913704
3  Sneha  35.000000     40.0  45.000000         0.000000
4  Rahul  95.000000     79.0  90.000000         1.000000
5  Pooja  88.000000     92.0  87.000000         0.883333
6   Neha  76.000000     75.0  81.333333         0.683333
7  Arjun  89.822222     85.0  89.000000         0.913704
8  Vikas  84.000000     80.0  77.000000         0.816667
9  Meera  91.000000     88.0  93.000000         0.933333